# Generated by Django 3.1.3 on 2020-11-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20201129_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza_image',
            options={'verbose_name_plural': 'Pizza Images'},
        ),
    ]
