# Generated by Django 3.1.3 on 2020-11-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20201129_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_image',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
