# Generated by Django 3.1.3 on 2020-11-29 07:09

from django.db import migrations, models
import django.db.models.deletion
import pizzas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_pizza_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_image',
            name='pizza_img',
            field=models.ImageField(upload_to=pizzas.models.upload_location),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza')),
            ],
            options={
                'verbose_name_plural': 'models',
            },
        ),
    ]
