# Generated by Django 3.1.3 on 2020-11-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20201129_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
